### ISSUE TITLE
where is qmake?

### ISSUE THREAD

**Issue by fedelibre** [flathub/com.riverbankcomputing.PyQt.BaseApp#101]
I'm building a dependency which needs to know the path to qmake, but I cannot find it in this BaseApp:

```
[📦 com.riverbankcomputing.PyQt.BaseApp ~]$ find / -name qmake
find: '/proc/tty/driver': Permission denied
[📦 com.riverbankcomputing.PyQt.BaseApp ~]$
```

Am I searching in the wrong place?

**Comment by JakobDev** [comment]
qmake is not part of this BaseApp. Its is included in the KDE SDK. If you need qmake, use `org.kde.Sdk` instead of  `org.kde.Runtime`. This BaseApp is compatible with both.

**Comment by fedelibre** [comment]
Of course, it should be in a Sdk. Sorry for the noise.
