### ISSUE TITLE
python-packaging is removed even if my app depends on it

### ISSUE THREAD

**Issue by cbm755** [flathub/com.riverbankcomputing.PyQt.BaseApp#12]
I'm no expert on flatpak so please forgive me if this is user error.

In the build log I see:
```
...
removed directory '/app/lib/python3.9/site-packages/packaging'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/INSTALLER'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/WHEEL'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/LICENSE'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/LICENSE.APACHE'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/top_level.txt'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/LICENSE.BSD'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/RECORD'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/METADATA'
removed '/app/lib/python3.9/site-packages/packaging-21.3.dist-info/REQUESTED'
removed directory '/app/lib/python3.9/site-packages/packaging-21.3.dist-info'
...
```

But my app actually needs that library.  So then my app fails to run:
```
Traceback (most recent call last):
  File "/app/bin/PlomClient", line 12, in <module>
    from plom.client.__main__ import main
  File "/app/lib/python3.9/site-packages/plom/client/__init__.py", line 15, in <module>
    from .chooser import Chooser
  File "/app/lib/python3.9/site-packages/plom/client/chooser.py", line 21, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

I include my own `python3-packaging.json` (same as my other python lib dependencies).

Downstream this is https://github.com/flathub/org.plomgrading.PlomClient/pull/56

**Comment by tinywrkb** [comment]
Thanks for reporting, and sorry that an oversight. I'll merge #13 after a successful CI run. The publishing delay here is set on 1 hour, but over 2 hours is more realistic.

**Comment by cbm755** [comment]
No hurry just trying to do my part to help out!

**Comment by tinywrkb** [comment]
For some reason, the [x86_64 build](https://flathub.org/builds/#/builders/35/builds/10487) was not uploaded, so the latest published build does not include python-packaging.  
I triggered build [87740](https://flathub.org/builds/#/builders/32/builds/87740), which was successful, and it should be published in about an hour.
