### ISSUE TITLE
Question about update workflow

### ISSUE THREAD

**Issue by vchernin** [flathub/com.riverbankcomputing.PyQt.BaseApp#18]
This isn't a real issue, just asking about the update workflow since I was looking to add a runtime (and baseapp) checker to f-e-d-c. Perhaps updating `x-base-commit` is worth supporting there (albeit this seems to be the only app on flathub to use `x-base-commit`).

Since you can only update this baseapp once the new `io.qt.qtwebengine.BaseApp` is actually published, I'm unsure why the workflow needs the commit of the latest unpublished `io.qt.qtwebengine.BaseApp`, i.e. `BASEAPP_COMMIT_BUILT`. Could you clarify why it's useful, why this condition is checked?:
https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp/blob/f0d606e6c591a849a833c60ec9c77c1938d0975a/.github/workflows/update.yaml#L227

My assumption is since it checks every 4 hours, if there is an unpuslished `io.qt.qtwebengine.BaseApp` the workflow could wait in a loop until the build is published, and then send the PR? But why not just check the latest published build, and run the workflow every 30 minutes or so?

**Comment by tinywrkb** [comment]
The idea is to avoid unneeded rebuilds when the `x-base-commit` property is outdated, but the latest `PyQt.BaseApp` build is actually using the most recent published `qtwebengine.BaseApp`.  

Let's say there's a PR for `PyQt.BaseApp` waiting to be merged. This PR might have been created for updating a module or trigger a rebuild with updated `qtwebengine.BaseApp` (and updating `x-base-commit`).  
In between of the maintainer merging the PR a new `qtwebengine.BaseApp` was published.  
If you merge the PR before the workflow creates a new PR with the `x-base-commit` change, then you will have a `PyQt.BaseApp` built with a more recent `qtwebengine.BaseApp` than the value of `x-base-commit` in the source repo.

`BASEAPP_COMMIT_LATEST` is the latest commit of `qtwebengine.BaseApp` in Flathub, which we get with `flatpak remote-info --system --show-commit`.  
`BASEAPP_COMMIT_BUILT` is the commit of `qtwebengine.BaseApp` that was pulled into the latest published `PyQt.BaseApp`, which is the value of `base-commit` property from `manifest.json` that is distributed with `PyQt.BaseApp`, and we use ostree's `pull` and `checkout` commands directly to avoid unneeded network transfer and disk operations.

You can have shorter intervals between each workflow run, but then you might trigger unneeded PRs that only update `x-base-commit` when an already open PR will trigger a rebuild with the most recent `qtwebengine.BaseApp` published build.

**Comment by tinywrkb** [comment]
And this workflow does have a few shortcomings, not to mention that the beta branch handling is wrong.  
It will be much better to implement this in f-e-d-c, but I didn't know if I have the time to look into coding this now with my very limited Python know how, and will have looked into it much later.

**Comment by vchernin** [comment]
Thanks for the info, this makes a lot more sense now.

Another question, why store `x-base-commit` in the first place (i.e. `BASEAPP_COMMIT_STORED`)? Since `x-base-commit` doesn't actually control what is used for the build, I find it a bit confusing. I think it may be best to not use it at all.

Instead I suggest this:

Attempt to make a rebuild change PR if:
1. There are no building or unpublished `PyQt.BaseApp` builds
2. `BASEAPP_COMMIT_LATEST` != `BASEAPP_COMMIT_BUILT`

a) If there are no other f-e-d-c changes:
 `git commit --allow-empty` should allow making a PR with no real changes, solely used for a rebuild, a "rebuild PR". The PR description could mention merging the empty change is a way to rebuild the app with the latest baseapp, which is why it never opens new prs once there is an existing rebuild PR.

b) If there are other f-e-d-c changes but there is an existing identical branch: 
Comment on that PR, explaining that merging it will cause the app to use a different version of the baseapp. It could maybe just remake the PR to be consistent with the other cases though.

c) If there are other f-e-d-c changes and no existing identical branch: 
Just make a new PR as usual, except mention in the PR description this will cause the app to use a different version of the baseapp.

This should avoid (most) unneeded PRs since we are checking for building or unpublished builds. The current branch name using `git rev-parse HEAD^{tree}` should avoid opening a rebuild PR multiple times, consistent with the way the external data checkers behave. 

Does this seem reasonable?

**Comment by tinywrkb** [comment]
> Another question, why store x-base-commit in the first place (i.e. BASEAPP_COMMIT_STORED)? Since x-base-commit doesn't actually control what is used for the build, I find it a bit confusing. I think it may be best to not use it at all.

For logging and to detail that one of the reasons the PR was created is a base application (qtwebengine.BaseApp) update.  
As the workflow has no control on the content of the commit created by f-e-d-c, then the only way to log this is with a separate commit.  
The maintainer might decide that the changes in f-e-d-c PR are not worth pushing an update to users, and build that application again, so the PR will be closed not knowing it also updates the base application.

> Does this seem reasonable?

Yes, sounds great. There's nothing else I have to add to your suggestion.

**Comment by tinywrkb** [comment]
Worth noting that I planned to use the same workflow for the qutebrowser application, which is why there's an initial implementation of beta branch/flathub-beta handling.  
It will have beta version built from git that will use PyQt6 (stable uses PyQt5).

**Comment by vchernin** [comment]
Good to hear this seems reasonable. I might try to implement it as part of the "runtime checker" then. 

This should probably be a disabled by default feature though, enabled by passing some flag. I figure most maintainers would not want "rebuild PRs". But if they do, it requires f-e-d-c to slowly rollout rebuild PRs in order to not overwhelm the builders, and then the feature wouldn’t be as helpful.

> Worth noting that I planned to use the same workflow for the qutebrowser application, which is why there's an initial implementation of beta branch/flathub-beta handling.

Yeah, I think this can be also be done with f-e-d-c, it can use flathub-beta if the checked out branch is beta.

**Comment by tinywrkb** [comment]
Right, better have this as opt-in.

**Comment by tinywrkb** [comment]
Closing as this is not an issue, and I probably will drop this `x-base-commit` approach and replace it with f-e-d-c wrapper, as I also need the wrapper for flatpak-builder-tools automation.

**Comment by JakobDev** [comment]
I think Flathub should automagically rebuild on every BaseApp update. Especially when using Qt WebEngine, which may have important security updates. This should be implement at Flathub site and not be part of each BaseApp.

**Comment by tinywrkb** [comment]
QtWebEngine should have been in the runtime or as a runtime extension.
