### ISSUE TITLE
Set component type in metainfo file

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.riverbankcomputing.PyQt.BaseApp#282]
at least generic or runtime.

**Comment by bbhtt** [comment]
@JakobDev Please don't rebuild or push to any branch without fixing this and verifying the fix https://github.com/ximion/appstream/issues/609

**Comment by JakobDev** [comment]
I have now set the type to generic

**Comment by bbhtt** [comment]
Thanks, this was fixed in the backend too.
