### ISSUE TITLE
Breaks when accessing QFileDialog in 6.7 on KDE 6

### ISSUE THREAD

**Issue by rafatosta** [flathub/com.riverbankcomputing.PyQt.BaseApp#328]
After updating to KDE 6, my [ZapZap](https://flathub.org/apps/com.rtosta.zapzap) application is breaking when accessing the QFileDialog to open and save files.

In the logs, there is no mention of an error and so I don't know how to fix it on my side since I am coding according to the Qt 6.7 documentation.

I discovered that it is a problem with QFileDialog and versions 6.7 and 6.6 running on KDE 6, as version 6.5 works perfectly on KDE 6.

Another point, for information, is that using Fedora's PyQt packaging the problem also occurs, however installing PyQt via python-pip works on KDE 6.

I don't know what to do and how to solve this problem, as it seems to be a problem on the Qt6 + KDE 6 side.

Thank you very much for your attention and sorry if this is not the correct place to report the problem.

**Comment by JakobDev** [comment]
What do you mean with "breaks"?

**Comment by rafatosta** [comment]
> What do you mean with "breaks"?

The application closes and there is no record of the reason in the log

**Comment by rafatosta** [comment]
> What do you mean with "breaks"?

The application closes and there is no record of the reason in the log

**Comment by JakobDev** [comment]
Can you reproduce this with a minimal example?

**Comment by rafatosta** [comment]
As requested, I created a small example and put it in the repository:
https://github.com/rafatosta/TestAppQFileDialog

I am using the same code in both and my application does not work. In the example it works correctly. It's something strange that is complicated to describe.

The only fact I got was that it works at 6.5 and no longer works at 6.7.

**Comment by rafatosta** [comment]
The problem is that in Qt 6.7 is not accepting to style the Qwidget.
`QWidget{
            color: red;
 }
`
 That is, when applying any property, QFileDialog does not open and the app is closed to seek.

Excuse and thanks for your attention
