### ISSUE TITLE
QtPdf not available

### ISSUE THREAD

**Issue by fedelibre** [flathub/com.riverbankcomputing.PyQt.BaseApp#362]
Can you please add QtPdf?
I'm building a beta branch of an app that now requires `PyQt6.QtPdf` to display PDFs.

See:
- https://github.com/frescobaldi/qpageview/issues/27
- https://github.com/flathub/org.frescobaldi.Frescobaldi/pull/60

**Comment by JakobDev** [comment]
I've added QtPdf in #365. Could you test the build of this PR?

**Comment by fedelibre** [comment]
I've just tested it and I confirm that now Frescobaldi runs correctly.

Please merge it, thanks

**Comment by JakobDev** [comment]
> Please merge it, thanks

Done
