### ISSUE TITLE
Add 6.8 branch

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.riverbankcomputing.PyQt.BaseApp#386]
Please consider adding the `6.8` runtime branch. Thanks!

**Comment by AsciiWolf** [comment]
@JakobDev Any chance this could be done? I have a quite important Flatpak (with over 1M users) that depends on this PyQt BaseApp and cannot be updated to 6.8.

**Comment by JakobDev** [comment]
Sorry, I missed the Notification last Week.

The reason there's no 6.8 branch of the BaseApp is simple: There's no 6.8 version of PyQt yet. On PyPI it's still on Version 6.7.1. There are currently only development Snapshots, which might cause Issues. So until there's a stable Release of PyQt 6.8 ([which might be delayed until Qt 6.8.1 is out](https://www.riverbankcomputing.com/pipermail/pyqt/2024-October/046045.html)) ,there won't be a 6.8 branch.

**Comment by AsciiWolf** [comment]
Ah, thanks for the info!

**Comment by JakobDev** [comment]
A 6.8 branch is now available
